### PR TITLE
Introducing PeriodicEvents instead of EventTriggers

### LINKED ISSUE #421: Calculating start of semester correctly
Today, we've received a report that the evaluation form has closed on 31st January instead of 3rd February. I could reopen it only by setting `send_status_statement_request` in the `event_triggers` table from 7th May to 7th October.

My suspect is the `isEvaluationAvailable` function in `SemesterEvaluationController`. Particularly this point:

```php
public static function isEvaluationAvailable(): bool
{
    $available = EventTrigger::find(EventTrigger::SEMESTER_EVALUATION_AVAILABLE)->date;
    $deadline = self::deadline();

    return now() <= $deadline && $available >= Semester::next()->getStartDate();
}
```

I'll check this out.

### PR DESCRIPTION
**Pull request by kdmnk**
See https://github.com/EotvosCollegium/mars/issues/421#issuecomment-2035019754 for the description behind the idea.
The HasPeriodicEvent trait is going to be used by controllers (eg. ApplicationController)
Other PRs will come to update the existing logic (applications, semester evaluation, etc) one by one. 
I just seperated it to multiple PRs, which also means that some test cases are commented out temporarily.
I'll post these in some days in case it's hard to understand without the use cases (or you can check here: https://github.com/EotvosCollegium/mars/pull/525).
Please let me know if you have questions so I can improve the readablity

## Summary by CodeRabbit

- **New Features**
  - Introduced periodic event handling, including start, reminder, and end actions.
  - Added new email notifications for evaluation form availability, reminders, and closure.
  - Added functionality to manage voting periods and application deadlines.

- **Bug Fixes**
  - Updated validation keys and translations in English and Hungarian language files.

- **Tests**
  - Enhanced test coverage for periodic events and status updates.
  - Added new test methods for `PeriodicEvent` and related functionalities.

- **Chores**
  - Updated `.gitignore` to include new directories.
  - Adjusted environment variable configurations in `.env.example`.

- **Documentation**
  - Updated documentation to reflect new methods and functionalities for periodic events and evaluations.

### CODE REVIEW

**Review by sszajbely — APPROVED** [review]

**Comment by kdmnk** [comment]
@viktorcsimma is this understandable for you?
You can check how I use this for example at the SemesterEvaluationController (as that is the most advanced) here: [app/Http/Controllers/Secretariat/SemesterEvaluationController.php](https://github.com/EotvosCollegium/mars/pull/533/files#diff-702ded7b489b0117c243b28ea67c2b8c7af77376b52f1425849093ba28a0154f)

**Comment by kdmnk** [comment]
I merged in the modified controllers that uses this, so now it's a fairly big PR. 
I'm ready to merge and test on staging, but I'd still appreciate some feedback regarding readability.

**Comment by viktorcsimma** [comment]
@kdmnk oh, I see... so we have this interface-like thing, through whose methods we can control what happens when. It's nice:) and I think it's also easy to understand.

**Comment by kdmnk** [comment]
@horcsinbalint please let me know when can I test it on the test server, if that's available

**Comment by horcsinbalint** [comment]
> @horcsinbalint please let me know when can I test it on the test server, if that's available

I will try to achieve this during the day

**Comment by horcsinbalint** [comment]
It does not work after logging in to the staging system: #544

**Pull request merged**
