### PR TITLE
Letting tenants view rooms

### PR DESCRIPTION
**Pull request by viktorcsimma**
As in the title. Based on a user request.

### CODE REVIEW

**Comment by kdmnk** [comment]
I don't know if the collegists can see tenants now, but I'm not sure if the people want that anyone in the building can see where do they live. Thoughts?

**Comment by viktorcsimma** [comment]
As far as I can see, neither collegists see tenants nor vice versa.

Actually, it's a wish of some former collegists who want to interact with people inside. Maybe we could tie this to the alumni role. WDYT?

**Comment by kdmnk** [comment]
> As far as I can see, neither collegists see tenants nor vice versa.

Then what's the point of this issue?
btw, I just wanted to raise my concerns, I don't really care or want to make a statement. Ask the student council what makes sense.

The code itself is fine, I'll approve it

**Review by kdmnk — APPROVED** [review]

**Comment by viktorcsimma** [comment]
It's been voted down; I close this. Probably we should solve these user requests individually.

**Pull request closed without merging**
