### PR TITLE
Added missing students section for general assemblies

### LINKED ISSUE #499: Add a list of missing students to general assemblies
It would be needed for the records the secretary writes. If you want, you can write it in a way only authorised people see it (so the president, the secretary and admins); but there are arguments for and against that;)

If this could be done for the next assembly on 4th April, that would be nice.

### PR DESCRIPTION
**Pull request by horcsinbalint**
## Description
Added missing students section
## Related Issue
#499
## Changes
- Added table for students that should attend general assemblies
- List students that are missing

### CODE REVIEW

**Comment by viktorcsimma** [comment]
Maybe I miss the point, but wouldn't it be easier to connect this with #482? That way, we would know exactly who was a collegist at that time, and from the status, we would also know whether they were active in the semester.

**Comment by horcsinbalint** [comment]
> Maybe I miss the point, but wouldn't it be easier to connect this with #482? That way, we would know exactly who was a collegist at that time, and from the status, we would also know whether they were active in the semester.

You are right, my implementation stores whether they were enrolled at the time which could be done easier if #482 was fixed.

**Comment by kdmnk** [comment]
Just took a quick look. Yes, I don't see why storing the users in a new table is necessary. We already have everything for this in the statuses. Just make a new relation between general assemblies and semesters. Anyone who is active and not excused is supposed to be there, right?

**Comment by horcsinbalint** [comment]
> Just took a quick look. Yes, I don't see why storing the users in a new table is necessary. We already have everything for this in the statuses. Just make a new relation between general assemblies and semesters. Anyone who is active and not excused is supposed to be there, right?

Yes, if alumnis are never considered active. Idk, it might be the case. I was not really sure if there could be a case where alumnis / guests have an active status as previously there was a filter in the code for non-alumni collegists. But yes, it seems to be redundant.

Is there a way for us to get the semester for a given date or we should store the semester for the GeneralAssembly object?

**Comment by kdmnk** [comment]
Add a semester_id. It will fit with the new semester behaviour I'm working with.
Statuses and roles are not connected but without human intervention we should not have an active alumni. Worst case, someone will find them in this list and update them so it's not a big deal.

**Comment by horcsinbalint** [comment]
Closing for lack of motivation to implement the requested changes. I still think that this is a useful addition, but I don't have the time to add large changes which are outside the scope of the bug I'm trying to fix.

**Pull request closed without merging**
