### PR TITLE
Deploying recent changes, mostly related to applications

### PR DESCRIPTION
**Pull request by viktorcsimma**
As in the title.

It's a draft until #581 gets merged; but from then on we can test it on staging. Maybe we could ask someone from the Students' Council to try it too (though they are quite busy right now).

### CODE REVIEW

**Comment by BertalanD** [comment]
Can this go into staging first? I'd like to thoroughly test any registration/admission-related code before it starts causing issues with TTT or prospective students.

**Comment by BertalanD** [comment]
as in: sit down tomorrow night and start the application period on the staging instance, and manually go through the admissions process for a fake user.

**Comment by viktorcsimma** [comment]
Yes, that would be nice:) Just merge it into staging manually; we don't need a PR for that. And thanks in advance 😊

**Comment by viktorcsimma** [comment]
I'll get the tests pass tonight with a separate PR.

**Comment by viktorcsimma** [comment]
Should I still check out the tests? I have done #589 but I now see you've made progress since then.

**Pull request merged**
