### PR TITLE
Fix issues with escapings with forms

### LINKED ISSUE #28: Fix epistola bugs
See https://github.com/luksan47/mars/issues/639

### PR DESCRIPTION
**Pull request by horcsinbalint**
There have been multiple issues with characters being escaped incorrectly. Check #28

It's better and easier to use textareas if someone needs to show previous user input since it is much more established how one can escape HTML as simple text on the page in PHP / Laravel compared to escaping inside of an attribute.
`x-input.textarea` has been also reworked to have a similar interface to `x-input.text` and also to use slots instead of attributes to show values input by the user (https://laravel.com/docs/10.x/blade#slots).

This PR should fix #28.

### CODE REVIEW

**Comment by horcsinbalint** [comment]
Fixed conflicts caused by #454

**Review by kdmnk — COMMENTED** [review]
So after this change when should one use the simple text field? Why don't we delete the simple text field and use only the textarea?

**Comment by horcsinbalint** [comment]
> So after this change when should one use the simple text field? Why don't we delete the simple text field and use only the textarea?

As I understand, currently our `x-input.text` implementation works and used as if it was just a fancy `<input>` tag. We use it for types other than `text` (like `number`). For them, `textarea`s would not be great (they work well with texts but they cannot have a different type).

I was planning on making a simple bugfix, and did not check whether some other components are necessary (like `datepicker`, `timepicker`). I'm not a master of tailwind-css, so I just tried to fix the problem that I came across. We should probably create a main `x-input.input` component, and parameterize it properly in other types of input components (like `datepicker`, `timepicker`, etc.). I will check on it.

I just now realized that I just removed the feature that can repopulate the forms in case of validation errors. I will check on that as well.

**Comment by kdmnk** [comment]
Yeah these input fields can be cumbersome to use. The main reason I added those to insert the validation messages automatically as those were easy to miss out (and to avoid writing some trivial tags). I'm open to other solutions here.

When working with input fields we need to keep the followings in mind:
- validation error message are shown
- previous value from database is prefilled
- previous session data is prefilled if exists (after validation error we keep the state)

I'm still sure we don't have all these everywhere yet as there are a lot of special cases.

**Comment by horcsinbalint** [comment]
Closing for lack of motivation to implement the requested changes. I still think that this is a useful addition, but I don't have the time to add large changes which are outside the scope of the bug I'm trying to fix.

**Pull request closed without merging**
